import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    SafeAreaView: {
      flex: 1,
      backgroundColor: '#0E6FFF',
    },
    container: {
      flex: 1,
    },
    header: {
      marginHorizontal: 20,
      top: 20,
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
    },
    Text: {
      color: '#FFFFFF',
      fontFamily: 'Figtree-SemiBold',
      fontSize: 24,
    },
    Image: {
      height: 40,
      width: 40,
    },
    content: {
      flex: 1,
      top: 50,
      backgroundColor: '#F5F5F5',
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
    },
    firstContainer: {
      marginHorizontal: 20,
    },
    wish: {
      paddingTop: 20,
      color: '#999CA0',
      fontFamily: 'Figtree-Regular',
      fontSize: 16,
    },
    name: {
      color: '#000000',
      fontFamily: 'Figtree-SemiBold',
      fontSize: 24,
      paddingRight: 8,
    },
    wave: {
      height: 28,
      width: 28,
    },
    graph: {
      backgroundColor: '#FFFFFF',
      borderRadius: 8,
      marginTop: 20,
      paddingTop: 20,
      paddingHorizontal: 20,
      marginHorizontal: 20,
    },
    subhead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    weather: {
      color: '#999CA0',
      fontFamily: 'Figtree-Regular',
      fontSize: 14,
    },
    box: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      padding: 5,
      gap: 4,
      borderRadius: 1,
      borderColor: '#00000014',
    },
    time: {
      height: 16,
      width: 16,
    },
    chart: {
      width: '100%',
    },
    logo: {
      height: 32,
      width: 32,
    },
    list: {
      backgroundColor: '#FFFFFF',
      paddingTop: 20,
      paddingRight: 20,
      paddingLeft: 20,
      paddingBottom: 10,
      borderRadius: 8,
    },
    subheader: {
      color: '#000000',
      fontFamily: 'Figtree-SemiBold',
      fontSize: 16,
      lineHeight: 24,
      paddingTop: 20,
    },
    arrow: {
      height: 32,
      width: 32,
    },
    analytics: {
      marginHorizontal: 20,
      marginTop: 40,
      marginBottom: 20,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderRadius: 8,
      padding: 10,
      borderColor: '#D8D8D8',
    },
    text2: {
      color: '#000000',
      fontFamily: 'Figtree-SemiBold',
      fontSize: 16,
      lineHeight: 24,
      paddingLeft: 10,
    },
    buttonGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 10,
      backgroundColor: '#fff',
    },
    button: {
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 20,
      marginRight: 10,
    },
    selectedButton: {
      backgroundColor: '#0E6FFF',
    },
    buttonText: {
      color: '#999CA0',
      fontSize: 16,
      fontFamily: 'Figtree-SemiBold',
    },
    selectedButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontFamily: 'Figtree-SemiBold',
    },
    searchIcon: {
      height: 36,
      width: 36,
    },
    contentContainer: {
      flex: 1,
      marginTop: 10,
      height: 580,
    },
    itemContainer: {
      backgroundColor: '#FFFFFF',
      marginVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#e0e0e0',
      marginHorizontal: 20,
    },
    itemHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    icon: {
      width: 48,
      height: 48,
      marginRight: 10,
    },
    itemTitle: {
      fontSize: 14,
      fontFamily: 'Figtree-Regular',
      lineHeight: 24,
      color: '#000000',
    },
    itemDate: {
      color: '#999CA0',
      fontFamily: 'Figtree-Regular',
      fontSize: 12,
      lineHeight: 18,
    },
    clicksContainer: {
      alignItems: 'flex-end',
    },
    clicks: {
      fontSize: 14,
      fontFamily: 'Figtree-Regular',
      lineHeight: 24,
      color: '#000000',
    },
    clicksLabel: {
      color: '#999CA0',
      fontFamily: 'Figtree-Regular',
      fontSize: 12,
      lineHeight: 18,
    },
    urlContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 10,
      backgroundColor: '#E8F1FF',
      borderBottomLeftRadius: 10,
      borderBottomRightRadius: 10,
      borderStyle: 'dashed',
      borderWidth: 1,
      borderColor: '#A6C7FF',
      paddingHorizontal: 10,
    },
    url: {
      color: '#0E6FFF',
      fontSize: 14,
      fontFamily: 'Figtree-Regular',
      lineHeight: 16,
    },
    copyButton: {
      padding: 5,
    },
    copyIcon: {
      height: 24,
      width: 24,
    },
    noLinksContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 200,
    },
    noLinksText: {
      color: '#8e8e8e',
      fontSize: 16,
    },
    link: {
      marginHorizontal: 20,
      marginTop: 20,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderRadius: 8,
      padding: 10,
      borderColor: '#D8D8D8',
    },
    whatsapp: {
      marginHorizontal: 20,
      marginTop: 40,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderRadius: 8,
      padding: 15,
      borderColor: '#D8D8D8',
      backgroundColor: '#4AD15F52',
      gap: 10,
    },
    questions: {
      marginBottom: 200,
      marginHorizontal: 20,
      marginTop: 20,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderRadius: 8,
      padding: 15,
      borderColor: '#D8D8D8',
      backgroundColor: '#0E6FFF52',
      gap: 10,
    },
  });
  export default styles;